apiVersion: 1
contactPoints:
  - orgId: 1
    name: slack-primary
    receivers:
      - uid: slack-primary
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          username: grafana
          recipient: ${SLACK_CHANNEL}
          icon_emoji: ":rotating_light:"
  - orgId: 1
    name: pagerduty-primary
    receivers:
      - uid: pagerduty-primary
        type: pagerduty
        settings:
          integrationKey: ${PAGERDUTY_ROUTING_KEY}

notificationPolicies:
  - orgId: 1
    receiver: slack-primary
    group_by: ["service", "env"]
    matchers:
      - { label: severity, match: =, value: warn }
  - orgId: 1
    receiver: pagerduty-primary
    group_by: ["service", "env"]
    matchers:
      - { label: severity, match: =, value: critical }
